# .github/workflows/callable_workflow.yml

name: Callable Workflow

on:
  workflow_call:
    inputs:
      url:
        description: 'URL to curl'
        required: true
        type: string

jobs:
  run-curl:
    runs-on: ubuntu-latest
    steps:
      - name: Run curl command
        run: |
          curl "${{ github.event.inputs.url }}"
